apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: comic-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
        - name: frontend
          image: localhost:5000/comic-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              value: "http://backend.comic-prod.svc.cluster.local:8000"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: comic-prod
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: frontend
