apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: comic-gateway
  namespace: comic-prod
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts: ["*"]
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: comic-routing
  namespace: comic-prod
spec:
  hosts: ["*"]
  gateways: ["comic-gateway"]
  http:
    - match:
        - uri:
            prefix: "/api/"
      route:
        - destination:
            host: backend
            port:
              number: 8000
    - match:
        - uri:
            prefix: "/health"
      route:
        - destination:
            host: backend
            port:
              number: 8000
    - route:
        - destination:
            host: frontend
            port:
              number: 3000
