apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: comic-prod

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - minio.yaml
  - backend.yaml
  - worker.yaml
  - frontend.yaml
  - istio.yaml
  - cloudflared.yaml
  - cookie-sync-configmap.yaml

secretGenerator:
  - name: comic-secrets
    envs:
      - .env.shared
    options:
      disableNameSuffixHash: true
